name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: METRICS_TOKEN
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          filename: metrics_left.*
          template: classic
          repositories_forks: yes
          base_indepth: yes
          plugin_lines: yes
          plugin_rss: yes
          plugin_rss_limit: 4
          plugin_anilist: yes
          plugin_anilist_user: keyu98

      - name: Right Part
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics_right.*
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.METRICS_TOKEN }}
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_notable_indepth: yes
          plugin_activity: yes
