name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: METRICS_TOKEN
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          filename: metrics_left.*
          template: classic
          repositories_forks: yes
          base_indepth: yes
          plugin_lines: yes

      - name: Right Part
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics_right.*
          base: ""
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_notable_indepth: yes
          plugin_activity: yes
          plugin_activity_skipped: keyu98/keyu98
          plugin_activity_days: 10000
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_filter: pr
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_repositories: yes
          plugin_repositories_featured: git/git, eclipse-jgit/jgit
          plugin_repositories_order: featured, pinned, starred, random
